//
//  LoginSceneViewController.swift
//  FalabellaFinancieroTest
//
//  Created Juan Guillermo Quiroga Salamanca on 5/12/20.
//  Copyright © 2020 Globant. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class LoginSceneViewController: UIViewController, LoginSceneViewProtocol {

	var presenter: LoginScenePresenterProtocol

	init(presenter: LoginScenePresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "LoginSceneViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
    }

}
