//
//  DetailSceneViewController.swift
//  FalabellaFinancieroTest
//
//  Created Juan Guillermo Quiroga Salamanca on 5/13/20.
//  Copyright © 2020 Globant. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

protocol DetailSceneViewProtocol: class {
    func loadStoreData()
}

final class DetailSceneViewController: BaseViewController, MVPView {

	lazy var presenter: DetailScenePresenterProtocol = self.inject()
    var store: StoreData?
    lazy var router: Router = self.inject()
    
    @IBOutlet weak var countyLabel: UILabel!
    
    @IBOutlet weak var phoneLabel: UILabel!
    @IBOutlet weak var stateLabel: UILabel!
    
    @IBOutlet weak var storeNameLabel: UILabel!
    
    @IBOutlet weak var openStoreLabel: UILabel!
    
    @IBOutlet weak var openStoreTimeLabel: UILabel!
    
    @IBOutlet weak var closeStoreTimeLabel: UILabel!
    
    @IBOutlet weak var storeAddressLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        
    }
    
    @IBAction func backAction(_ sender: Any) {
        router.backToListScene()
        print("baaaaaakkkkk")
    }
    

}

private extension DetailSceneViewController{
    func setupView(){
        guard let _store = store else {return}
        countyLabel.text = _store.countyName
        phoneLabel.text = _store.storePhone
        stateLabel.text = _store.siteName
        storeNameLabel.text = _store.storeName
        openStoreLabel.text = _store.storeOpenTime
        closeStoreTimeLabel.text = _store.storeClosetime
        storeAddressLabel.text = _store.storeAddress
    }
}

extension DetailSceneViewController: DetailSceneViewProtocol {
    func loadStoreData() {
        
    }
    
    
}
