//
//  DetailScenePresenter.swift
//  FalabellaFinancieroTest
//
//  Created Juan Guillermo Quiroga Salamanca on 5/13/20.
//  Copyright © 2020 Globant. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: Presenter -
protocol DetailScenePresenterProtocol: class {

}

extension MVPView where Self: DetailSceneViewProtocol {
    func inject() -> DetailScenePresenterProtocol  {
        let presenter = DetailScenePresenter()
        presenter.view = self
        return presenter
    }
}

final class DetailScenePresenter: MVPPresenter {

    weak var view: DetailSceneViewProtocol?

    func viewDidLoad() {

    }
}

extension DetailScenePresenter: DetailScenePresenterProtocol {
    
}

